services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    startCommand: 'gunicorn taskmanager.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: taskmanager.settings
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite
